version: '2'

services:

  elasticsearch:
    container_name: "elasticsearch"
    image: elasticsearch:7.10.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
  redis:
    container_name: "regis"
    image: redis:3.0.1
    ports:
      - 6379:6379